### ISSUE TITLE
V20 Timeout

### ISSUE THREAD

**Issue by sameerk-k** [ftomassetti/backtrader-oandav20#10]
Received this error running tests against the Oanda practise env. The error was encountered after several hours of running successfully.

  File "/Applications/anaconda/lib/python3.6/site-packages/btoandav20/feeds/oandav20feed.py", line 286, in _load
    if 'code' in msg:
TypeError: argument of type 'V20Timeout' is not iterable

**Comment by happydasch** [comment]
At the moment, i won't be able to fix this issue, since this is a bigger thing. The way the streaming works at the moment, it is not possible to restore the connection, i believe.

I will move the error to store instead of being passed to data feed.

**Comment by happydasch** [comment]
Added settings to store to set timeouts for api poll and stream requests. Set them to None to disable timeouts or to a higher value than the default. 

stream_timeout=None, 
poll_timeout=none,
