### ISSUE TITLE
OHLC off by 1  

### ISSUE THREAD

**Issue by sameerk-k** [ftomassetti/backtrader-oandav20#12]
#Not sure if I am misssing a setting but the input data is off by one candle. The data shown below API is from the backtrader-oandav20 test code for AUD/CAD on Mar 28 with H1 compression and the data shown under Web Oanda is what is displayed in the Oanda test web account. Please note that I am in the EST timezone and have DST. Assuming Oanda is also in NY, it should be in EST and timezone should not be a factor.

API
Data0, 0504, 736781.666667, 2018-03-28T16:00:00.000000, 0.988090, 0.989560, 0.987650, 0.989500
Data0, 0505, 736781.708333, 2018-M3-28T17:00:00.000000, 0.989500, 0.989840, 0.988050, 0.988460
Data0, 0506, 736781.750000, 2018-03-28T18:00:00.000000, 0.988420, 0.989680, 0.988390, 0.989460
Data0, 0507, 736781.791667, 2018-03-28T19:00:00.000000, 0.989480, 0.989580, 0.988810, 0.989350
Data0, 0508, 736781.833333, 2018-03-28T20:00:00.000000, 0.989320, 0.990210, 0.989300, 0.989960

Web Oanda

16:00     0.98950, 0.98984, 0.98805, 0.98846
17:00     0.98946, 0.98968, 0.98838, 0.98946
18:00     0.98946, 0.98958, 0.98880, 0.98934
19:00     0.98934, 0.99021, 0.98930, 0.98996
20:00     0.98996, 0.99043, 0.98972, 0.98984

**Comment by happydasch** [comment]
The way backtrader handles time is described here. I will check my data, too since my time is not valid also. Which is not a problem when live trading.

https://www.backtrader.com/docu/timemgmt.html

Please give feedback when setting the timezone works for you.

**Comment by happydasch** [comment]
datakwargs = dict(
    timeframe=bt.TimeFrame.Minutes, compression=1,
    tz=pytz.timezone('Europe/Berlin')
)
this gives me the correct local time.
