### ISSUE TITLE
Get Cancel Notification if Market is Closed?

### ISSUE THREAD

**Issue by haimivan** [ftomassetti/backtrader-oandav20#14]
Hi,

I create a market order outside of trading hours. 
I can see that the order is created in `backtrader-oandav20`, and gets received by OANDA. 
I can see in the OANDA web trading platform, that the order gets immediately cancelled by OANDA:

```
Ticket	Type	Market	Units	Price	Half Spread Cost	Profit (EUR)	Commission	Balance	Date / Time
384	Order Cancelled		-	-	-	-	-	-	3/31/2018, 5:13:16 AM
383	Market Order	EUR/USD	10	-	-	-	-	-	3/31/2018, 5:13:16 AM
```

But I do not receive a notification in `backtrader-oandav20`. I would expect that somehow I get notified about that in `notify_order()`, but this is not the case.

Is this related to `backtrader-oandav20` or is this the way how `backtrader` works in general (as we do not get new data outside of trading hours)?

**Comment by happydasch** [comment]
This is mostly related to btoandav20. Will look into this together with the price issue. Tomorrow i have some time for this.

**Comment by haimivan** [comment]
Hi,

I just found the backtrader parameter `quicknotify`.

With the following change in `oandav20test.py`, I get a notification immediately:

        # Live data ... avoid long data accumulation by switching to "exactbars"
        # cerebro.run(exactbars=args.exactbars)
        cerebro.run(exactbars=args.exactbars,
                    quicknotify=True
                    )

From my point of view, you can close the issue. 

==========
References:
https://www.backtrader.com/docu/cerebro.html

**Comment by happydasch** [comment]
I understand. For this issue, you would receive the notification of the canceled trade if there would be a new data feed row. I will close this, but will check the transactions on a closed market tomorrow.

From the doc:
Broker notifications are delivered right before the delivery of the next prices. For backtesting this has no implications, but with live brokers a notification can take place long before the bar is delivered. When set to True notifications will be delivered as soon as possible (see qcheck in live feeds)
