### ISSUE TITLE
Starting Algorithm With Pending Order

### ISSUE THREAD

**Issue by haimivan** [ftomassetti/backtrader-oandav20#15]
Hi,

again this could be related to Backtrader... :-)

Before I start the script `oandav20test.py`, I create a `Buy Stop` order via the `OANDA Web Trading Platform` that will not be executed, because it's weekend.

Afterwards I start `oandav20test.py`.

How is it possible to recognize this existing (pending) order within the code?

**Comment by happydasch** [comment]
it is not possible. You will not be able to recognize orders which were created outside the session. The same goes for trades that were closed outside backtrader, they will also not get recognized. 

It will only process transactions, that were created by the _order_create method. It would be possible to fill backtrader with all open trades when starting, but this would require some work. Currently, the store will fetch open positions. This data is used to create a simulated order, so backtrader can close that position. 

At the moment, its good to close all pending stuff or open trades/positions before starting backtrader.

**Comment by haimivan** [comment]
Thanks for your reply.

I understand you correctly, that not being able to get existing `orders` and `trades`/`positions` during startup is not `backtrader` related, but the present behaviour of `backtrader-oandav20`? 

In my humble opinion, it would be very helpful to have such a feature, as otherwise any interruption of a running process of `oandav20test.py` (like `Forced network separation by the internet service provider`, own programming errors...) would force me to continue my trading manually.

I understand it very well, that intercepting a running algo program leeds to a high complexity, but my humble hope would be to have such a feature that looks during startup in the present state of the account to fill internal variables accordingly.

**Comment by happydasch** [comment]
Yes, this is store related. We have the possibility to fetch the information on startup and recreate pending orders and open trades via the api. From this data we could fill and prepare backtrader.

I have this already on my todo List but i will not be able to work on it in near future.

I need this to be able to close trades manually from oanda.

**Comment by happydasch** [comment]
I have commited a new version today, give it a try. This should work now :grinning:
