### ISSUE TITLE
How to get Tick Data?

### ISSUE THREAD

**Issue by haimivan** [ftomassetti/backtrader-oandav20#17]
Hi,

I want to use `backtrader-oandav20` for the following scenario:

1. work on a relatively long timeframe (e.g.: 4 hour candlestick)
2. once all the criteria are met, I want to create an order only when with the beginning of the next candlestick some price related criteria are met - and I do not want to wait another four hours to get that data.

So it seems that using these parameters (especially `--replay`) will decouple the events in `next()` from the 4 hour timeframe and somehow follow a tick based scheme. 

            "--data0", "EUR_USD",
            "--timeframe", "Hours",
            "--compression", "4",
            "--trade",
            "--broker",
            "--replay",

My questions would be:

1. Is this the best way to satisfy the conditions I have? 

2. Is it ok to take the `close` values in `next()` as `tick data` for that very moment in time?

Thanks in advance!

Additional info: for **_30 seconds_** candlesticks I get the following ohlc data in `next()` during live trading:

    Data0, 0526, 736797.605425, 2018-04-13T14:31:48.755079, 1.232620, 1.232880, 1.232620, 1.232880,      0, 0
    Data0, 0526, 736797.605430, 2018-04-13T14:31:49.173544, 1.232620, 1.232930, 1.232620, 1.232930,      0, 0
    Data0, 0526, 736797.605432, 2018-04-13T14:31:49.286881, 1.232620, 1.232940, 1.232620, 1.232940,      0, 0
    Data0, 0526, 736797.605439, 2018-04-13T14:31:49.966881, 1.232620, 1.232950, 1.232620, 1.232950,      0, 0
    Data0, 0526, 736797.605444, 2018-04-13T14:31:50.383364, 1.232620, 1.232950, 1.232620, 1.232940,      0, 0
    Data0, 0526, 736797.605450, 2018-04-13T14:31:50.845130, 1.232620, 1.232950, 1.232620, 1.232920,      0, 0
    Data0, 0526, 736797.605462, 2018-04-13T14:31:51.932038, 1.232620, 1.232950, 1.232620, 1.232890,      0, 0
    Data0, 0526, 736797.605505, 2018-04-13T14:31:55.595839, 1.232620, 1.232950, 1.232620, 1.232870,      0, 0
    Data0, 0526, 736797.605518, 2018-04-13T14:31:56.712167, 1.232620, 1.232950, 1.232620, 1.232870,      0, 0
    Data0, 0526, 736797.605519, 2018-04-13T14:31:56.812509, 1.232620, 1.232950, 1.232620, 1.232880,      0, 0
    Data0, 0526, 736797.605552, 2018-04-13T14:31:59.716355, 1.232620, 1.232950, 1.232620, 1.232920,      0, 0
    Data0, 0526, 736797.605555, 2018-04-13T14:31:59.919824, 1.232620, 1.232950, 1.232620, 1.232950,      0, 0
    Data0, 0526, 736797.605556, 2018-04-13T14:32:00.000000, 1.232620, 1.232950, 1.232620, 1.232950,      0, 0
    Data0, 0527, 736797.605583, 2018-04-13T14:32:02.377908, 1.232960, 1.232960, 1.232960, 1.232960,      0, 0
    Data0, 0527, 736797.605585, 2018-04-13T14:32:02.513011, 1.232960, 1.232960, 1.232960, 1.232960,      0, 0
    Data0, 0527, 736797.605591, 2018-04-13T14:32:03.097025, 1.232960, 1.232960, 1.232960, 1.232960,      0, 0
    Data0, 0527, 736797.605658, 2018-04-13T14:32:08.892387, 1.232960, 1.232960, 1.232910, 1.232910,      0, 0
    Data0, 0527, 736797.605712, 2018-04-13T14:32:13.510517, 1.232960, 1.232960, 1.232910, 1.232960,      0, 0
    Data0, 0527, 736797.605723, 2018-04-13T14:32:14.505975, 1.232960, 1.232960, 1.232910, 1.232940,      0, 0
    Data0, 0527, 736797.605819, 2018-04-13T14:32:22.753668, 1.232960, 1.232960, 1.232880, 1.232880,      0, 0
    Data0, 0527, 736797.605821, 2018-04-13T14:32:22.910506, 1.232960, 1.232960, 1.232870, 1.232870,      0, 0
    Data0, 0527, 736797.605837, 2018-04-13T14:32:24.304192, 1.232960, 1.232960, 1.232840, 1.232840,      0, 0
    Data0, 0527, 736797.605863, 2018-04-13T14:32:26.542472, 1.232960, 1.232960, 1.232800, 1.232800,      0, 0
    Data0, 0527, 736797.605883, 2018-04-13T14:32:28.266955, 1.232960, 1.232960, 1.232800, 1.232800,      0, 0
    Data0, 0527, 736797.605888, 2018-04-13T14:32:28.699783, 1.232960, 1.232960, 1.232800, 1.232800,      0, 0
    Data0, 0527, 736797.605896, 2018-04-13T14:32:29.440938, 1.232960, 1.232960, 1.232800, 1.232810,      0, 0
    Data0, 0527, 736797.605901, 2018-04-13T14:32:29.868938, 1.232960, 1.232960, 1.232800, 1.232830,      0, 0
    Data0, 0527, 736797.605903, 2018-04-13T14:32:30.000000, 1.232960, 1.232960, 1.232800, 1.232830,      0, 0
    Data0, 0528, 736797.605921, 2018-04-13T14:32:31.569371, 1.232880, 1.232880, 1.232880, 1.232880,      0, 0
    Data0, 0528, 736797.605931, 2018-04-13T14:32:32.434444, 1.232880, 1.232880, 1.232860, 1.232860,      0, 0
    Data0, 0528, 736797.605936, 2018-04-13T14:32:32.865210, 1.232880, 1.232880, 1.232810, 1.232810,      0, 0
    Data0, 0528, 736797.605938, 2018-04-13T14:32:33.007967, 1.232880, 1.232880, 1.232790, 1.232790,      0, 0
    Data0, 0528, 736797.606012, 2018-04-13T14:32:39.448498, 1.232880, 1.232880, 1.232760, 1.232760,      0, 0
    Data0, 0528, 736797.606040, 2018-04-13T14:32:41.843023, 1.232880, 1.232880, 1.232760, 1.232810,      0, 0
    Data0, 0528, 736797.606042, 2018-04-13T14:32:42.000164, 1.232880, 1.232880, 1.232760, 1.232860,      0, 0
    Data0, 0528, 736797.606085, 2018-04-13T14:32:45.753161, 1.232880, 1.232880, 1.232760, 1.232820,      0, 0
    Data0, 0528, 736797.606090, 2018-04-13T14:32:46.191843, 1.232880, 1.232880, 1.232760, 1.232820,      0, 0
    Data0, 0528, 736797.606120, 2018-04-13T14:32:48.807781, 1.232880, 1.232880, 1.232760, 1.232850,      0, 0
    Data0, 0528, 736797.606134, 2018-04-13T14:32:49.955592, 1.232880, 1.232880, 1.232760, 1.232800,      0, 0
    Data0, 0528, 736797.606150, 2018-04-13T14:32:51.373026, 1.232880, 1.232880, 1.232760, 1.232820,      0, 0
    Data0, 0528, 736797.606153, 2018-04-13T14:32:51.654869, 1.232880, 1.232880, 1.232760, 1.232850,      0, 0
    Data0, 0528, 736797.606161, 2018-04-13T14:32:52.289567, 1.232880, 1.232880, 1.232760, 1.232870,      0, 0
    Data0, 0528, 736797.606178, 2018-04-13T14:32:53.800100, 1.232880, 1.232880, 1.232760, 1.232820,      0, 0
    Data0, 0528, 736797.606180, 2018-04-13T14:32:53.964864, 1.232880, 1.232880, 1.232760, 1.232820,      0, 0
    Data0, 0528, 736797.606183, 2018-04-13T14:32:54.196084, 1.232880, 1.232880, 1.232760, 1.232840,      0, 0
    Data0, 0528, 736797.606228, 2018-04-13T14:32:58.132886, 1.232880, 1.232880, 1.232760, 1.232810,      0, 0
    Data0, 0528, 736797.606250, 2018-04-13T14:33:00.000000, 1.232880, 1.232880, 1.232760, 1.232810,      0, 0
    Data0, 0529, 736797.606299, 2018-04-13T14:33:04.249912, 1.232830, 1.232830, 1.232830, 1.232830,      0, 0

**Comment by happydasch** [comment]
Live data returns always tick. For the 30 seconds data, either it has rightedge=False (which will output tick data without resampling) or you did not resample the data.

For our question, i think, the backtrader forum is a better place for the question. I would try to do it this way:

-add data (without resampling)
-clone this data and resample it to 4 hours

In your strategy you can check both data feeds for changes. I don't think, you will need to use  replay.
