### ISSUE TITLE
Volume and Openinterest Always Zero During Livetrading?

### ISSUE THREAD

**Issue by haimivan** [ftomassetti/backtrader-oandav20#18]
Hi,

It seems that in `next()` the values for `self.data.volume[0]` and `self.data.openinterest[0]` are always zero during live trading.

Is it possible to change this?

Thanks in advance!

**Comment by happydasch** [comment]
This data is not available for live prices

**Comment by happydasch** [comment]
with candles = True in data feed, volume will be available. By using this, the data is delayed by interval (only complete candles will be used)
