### ISSUE TITLE
Resample Candles Have Gaps?

### ISSUE THREAD

**Issue by haimivan** [ftomassetti/backtrader-oandav20#22]
Hi,

I use the original script `oandav20text.py` from this project with these parameters:

    --token <TOKEN> --account <ACCOUNT> --data0 EUR_USD --timeframe Seconds --compression 5 --trade --broker --resample --fromdate 2018-05-18T20:00:00

I observe sometimes gaps in the old data. 
Example:
Between:

    2018-05-18T20:01:15.000000

and

    2018-05-18T20:01:25.000000

the second `20` is missing.

I suppose this is related to OANDA itself. Does somebody know whether this was always the case with OANDA?

Or do I have to supply a different parameter so that these gaps do not appear?

Thanks in advance!

    Data0, 0002, 736832.833449, 2018-05-18T20:00:10.000000, 1.176740, 1.176740, 1.176740, 1.176740,      1, 0, nan
    Data0, 0003, 736832.833565, 2018-05-18T20:00:20.000000, 1.176760, 1.176760, 1.176750, 1.176750,      3, 0, nan
    Data0, 0004, 736832.833681, 2018-05-18T20:00:30.000000, 1.176770, 1.176800, 1.176750, 1.176800,      5, 0, nan
    Data0, 0005, 736832.833738, 2018-05-18T20:00:35.000000, 1.176800, 1.176800, 1.176800, 1.176800,      2, 0, 1.176776
    Data0, 0006, 736832.833796, 2018-05-18T20:00:40.000000, 1.176800, 1.176800, 1.176800, 1.176800,      2, 0, 1.176778
    Data0, 0007, 736832.833854, 2018-05-18T20:00:45.000000, 1.176800, 1.176800, 1.176790, 1.176790,      2, 0, 1.176788
    Data0, 0008, 736832.833912, 2018-05-18T20:00:50.000000, 1.176810, 1.176810, 1.176800, 1.176800,      2, 0, 1.176798
    Data0, 0009, 736832.833970, 2018-05-18T20:00:55.000000, 1.176770, 1.176770, 1.176730, 1.176730,      2, 0, 1.176784
    Data0, 0010, 736832.834028, 2018-05-18T20:01:00.000000, 1.176720, 1.176760, 1.176720, 1.176760,      5, 0, 1.176776
    Data0, 0011, 736832.834086, 2018-05-18T20:01:05.000000, 1.176760, 1.176760, 1.176760, 1.176760,      6, 0, 1.176768
    Data0, 0012, 736832.834144, 2018-05-18T20:01:10.000000, 1.176760, 1.176770, 1.176760, 1.176770,      4, 0, 1.176764
    Data0, 0013, 736832.834201, 2018-05-18T20:01:15.000000, 1.176760, 1.176770, 1.176760, 1.176770,      2, 0, 1.176758
    Data0, 0014, 736832.834317, 2018-05-18T20:01:25.000000, 1.176800, 1.176860, 1.176800, 1.176860,      3, 0, 1.176784
    Data0, 0015, 736832.834606, 2018-05-18T20:01:50.000000, 1.176900, 1.176900, 1.176880, 1.176880,      9, 0, 1.176808
    Data0, 0016, 736832.834664, 2018-05-18T20:01:55.000000, 1.176870, 1.176870, 1.176820, 1.176820,      4, 0, 1.176820
    Data0, 0017, 736832.834722, 2018-05-18T20:02:00.000000, 1.176830, 1.176880, 1.176820, 1.176880,      5, 0, 1.176842

**Comment by happydasch** [comment]
Hi, you can fill the gaps. These gaps happen when there are no ticks.



https://community.backtrader.com/topic/549/resample-and-fill-gaps/11
