### ISSUE TITLE
Short Interruption of Internet Connection Stops Price Retrieval

### ISSUE THREAD

**Issue by haimivan** [ftomassetti/backtrader-oandav20#23]
Hi,

whenever after 24 hours my internet provider makes a forced separation of my line, afterwards no price data is retrieved anymore.

I thought that the last statement in https://github.com/ftomassetti/backtrader-oandav20/issues/10 meant, that with 

    stream_timeout=None,
    poll_timeout=none,

a short interruption of my internet connection will not harm the processing anymore.

Did I understand it wrong?

Thanks in advance!

**Comment by happydasch** [comment]
The reconnection will only be done on initialization, when the connection goes away while running, the oanda store will stop working. I will take a look about reconnection after initialization. The problem here is, that if the connection goes away, data for feed will be missing.

**Comment by happydasch** [comment]
In my last statement, there is a error. It is not only connecting on initialization, but the 2 values for timeout will be pushed to v20 api wrapper. Mixed it with an other project. Sorry.

It will still stop when there is a connection issue. I will have a look into that. For now you could set a cron job to restart Backtrader after 23:59

**Comment by haimivan** [comment]
thanks for taking care!
