### ISSUE TITLE
How do I install it in backtrader

### ISSUE THREAD

**Issue by martinfou** [ftomassetti/backtrader-oandav20#24]
Hello I was wondering where and How I should install your package ?

when I try to run it with my account and token I get the following error 

python3 oandav20test.py --account <account-goes-here> --token <token-goes-here> --data0 GBP_USD --resample --timeframe Minutes --compression 1 --no-backfill_start --stake 1000 --trade

Traceback (most recent call last):
  File "oandav20test.py", line 30, in <module>
    import btoandav20
ImportError: No module named 'btoandav20'

**Comment by happydasch** [comment]
the easiest would be just copying the btoandav20 directory into the directory where your script is in, you can find some more infos here:

https://stackoverflow.com/questions/4933224/how-to-install-a-python-library-manually
https://docs.python.org/3/install/index.html

Daniel
