### ISSUE TITLE
should be pricing.ClientPrice instead of pricing.Price

### ISSUE THREAD

**Issue by radezheng** [ftomassetti/backtrader-oandav20#26]
oandav20store.py
line 414:
for msg_type, msg in response.parts():
                # if msg_type == "pricing.Price":
                if msg_type == "pricing.ClientPrice":

**Comment by happydasch** [comment]
Thanks for the ticket. The msg_type is correct. This comes from streaming, there are two types: a heartbeat and the price.

I used this code as a base:
https://github.com/oanda/v20-python-samples/blob/master/src/pricing/stream.py

**Comment by happydasch** [comment]
Checking both msg_types now (Price, ClientPrice)
