### ISSUE TITLE
Get History with long period - Error 400 from API with Exceed max count

### ISSUE THREAD

**Issue by edesmars** [ftomassetti/backtrader-oandav20#28]
Hi there,

Great job with the Oanda wrapper.
I wanted to backtest a strategy and was selecting a long period for the backtesting and the script just hanged with nothing happening.

After a bit of research and debug, i found out that the call to get the history of the candles was asking for too many candles at once hence a 400 response with the following message:
`{
    "errorMessage": "Maximum value for 'count' exceeded"
}`

I worked through the code and realised that removing the "toTime" from the query was solving this issue though i'm not sure of the impact on other scenario. 

So I modified the file 'oandav20store.py' => function '_t_candles' to remove "toTime" from "dtkwargs" in the while loop with the following (though just not adding it to the dtkwargs might be a better solution but I was afraid of any unseen impact):
```
    def _t_candles(self, dataname, dtbegin, dtend, timeframe, compression,
                   candleFormat, includeFirst, onlyComplete, q):
        '''Callback method for candles request'''
        granularity = self.get_granularity(timeframe, compression)
        if granularity is None:
            q.put(None)
            return

        dtkwargs = {}
        if dtbegin is not None:
            dtkwargs['fromTime'] = dtbegin.strftime("%Y-%m-%dT%H:%M:%S.000000000Z")
            dtkwargs['includeFirst'] = includeFirst

        if dtend is not None:
            dtkwargs['toTime'] = dtend.strftime("%Y-%m-%dT%H:%M:%S.000000000Z")

        count = 0
        while True:
            count += 1
            if count > 1: dtkwargs['includeFirst'] = False
            try:
                if 'toTime' in dtkwargs:
                    del dtkwargs['toTime']
                response = self.oapi.instrument.candles(dataname,
                                                 granularity=granularity,
                                                 price=candleFormat,
                                                 **dtkwargs)
                candles = response.get('candles', 200)
            except Exception as e:
                self.put_notification(e)
                return

            dtobj = None
            for candle in candles:
                if not onlyComplete or candle.complete:
                    q.put(candle.dict())
                    dtobj = datetime.utcfromtimestamp(float(candle.time))

            if dtobj is not None:
                dtkwargs['fromTime'] = dtobj.strftime("%Y-%m-%dT%H:%M:%S.000000000Z")
            elif dtobj is None:
                break
            if len(candles) == 0:
                break

        q.put({})  # end of transmission'''
```

To reproduce this issue, you just need to use a store with the following values:
```
    DataFactory = store.getdata
    # from_date
    dtformat = '%Y-%m-%dT%H:%M:%S'
    fromdate = datetime.datetime.strptime("2017-10-01T00:00:00", dtformat)
    todate = datetime.datetime.strptime("2018-06-04T01:00:00", dtformat)

    datakwargs = dict(
        timeframe=bt.TimeFrame.Minutes,
        compression=15,
        qcheck=0.5,
        historical=True,
        fromdate=fromdate,
        todate=todate,
        bidask=True,

    )
    data0 = DataFactory(dataname="EUR_USD", **datakwargs)
```
Let me know what you think of the fix and I can do a PR if you wish. Just let me know how to proceed and what to test first. If I did anything wrong in the config to use the wrapper and there is no need for a fix , please let me know ! ;)

**Comment by edesmars** [comment]
Did a very quick test, removing:
```
        if dtend is not None:
            dtkwargs['toTime'] = dtend.strftime("%Y-%m-%dT%H:%M:%S.000000000Z")
```
is working as expected and remove this issue. I tested with a very long period but also with an extremely short period (4 candles) and both results were good.

**Comment by happydasch** [comment]
Thanks for the report - will look into this issue.

**Comment by happydasch** [comment]
Try the last committed version. I have changed the way to time is being checked. This did work for longer periods. Feel free to reopen this issue if it does not fix your issues.
