### ISSUE TITLE
How to Work With oandav20test.py? - Parameter --timeframe

### ISSUE THREAD

**Issue by haimivan** [ftomassetti/backtrader-oandav20#3]
Hi,

I try to make first steps with "oandav20test.py", but get difficulties.

How do I have to supply the "--timeframe" parameter properly? Using this:

    import sys
    sys.argv[1:] = [
        "--token", "123",
        "--account", "456",
        "--data0", "111"
               "--timeframe", "Minutes"  # , "1"
    ]

leads to an error:

`oandav20test.py: error: unrecognized arguments: Minutes`

Thanks in advance!

**Comment by happydasch** [comment]
you would run the example on the console:

python oandav20test.py --token "TOKEN" --account "ACCOUNT" --data0 EUR_USD --timeframe Minutes --compression 1

The example is based on the oandatest example from backtrader

**Comment by haimivan** [comment]
thanks!
