### ISSUE TITLE
backfill_from AttributeError '_env'

### ISSUE THREAD

**Issue by faroutxxx** [ftomassetti/backtrader-oandav20#35]
Im trying to do a backfill_from with bt.feeds.PandasData but gives me an error which I cant figure out the problem to:

`AttributeError: 'Lines_LineSeries_DataSeries_OHLC_OHLCDateTime_Abst' object has no attribute '_env'`

```
dataBackfill = bt.feeds.PandasData(dataname=dataframe)  

data = btoandav20.feeds.OandaV20Data(dataname=pair,reconnections=-1,reconntimeout=1,reconnect=True,qcheck= 0.05, backfill_from=dataBackfill,tz=pytz.timezone('Europe/London'), timeframe=bt.TimeFrame.Minutes, compression=1)
```

Any ideas what the issue would be?

Just so that you know the same file PandasData read in for the backfill_from works fine using ibstore.getdata().

**Comment by happydasch** [comment]
this seems like a backtrader issue with your strategy, without any code its hard to tell. Please provide more code for your issue.

**Comment by faroutxxx** [comment]
The code is below. The same works for ibstore.getdata()

```
class TestX(bt.Strategy):
    def __init__(self):
        pass
    
    def next(self):
        print(self.data.close[0])

def runstrat(args=None):
    pair = "EUR_USD"
    cerebro = bt.Cerebro()
    btoandav20.stores.OandaV20Store(token=apikey, account=acc, practice=True)
    filein = os.path.join(dir_path,"Data","Backtrader",pair+".h5")
    dataframe = pd.read_hdf(filein,"x")
    dataBackfill = bt.feeds.PandasData(dataname=dataframe) 
    data = btoandav20.feeds.OandaV20Data(dataname=pair,backfill_from=dataBackfill,timeframe=bt.TimeFrame.Minutes, compression=1)
    cerebro.adddata(data)
    cerebro.addstrategy(TestX)
    cerebro.run()
```

**Comment by happydasch** [comment]
could you also provide the file Data/Backtrader/instr.h5?

**Comment by faroutxxx** [comment]
Uploaded and output example below. As I said works fine with ibstore.getdata()

```

ipdb> dataframe
                              Close     High      Low     Open  Volume
Datetime                                                              
2018-09-18 21:15:00.000000  1.16681  1.16685  1.16655  1.16660    -1.0
2018-09-18 21:16:00.000000  1.16678  1.16681  1.16678  1.16681    -1.0
2018-09-18 21:17:00.000000  1.16677  1.16678  1.16677  1.16678    -1.0
2018-09-18 21:18:00.000000  1.16677  1.16677  1.16677  1.16677    -1.0
2018-09-18 21:19:00.000000  1.16677  1.16677  1.16677  1.16677    -1.0
```

[EUR_USD.h5.zip](https://github.com/ftomassetti/backtrader-oandav20/files/3631646/EUR_USD.h5.zip)

**Comment by happydasch** [comment]
Checkout the last commit

**Comment by happydasch** [comment]
Reopen if the fix does not work for you

**Comment by faroutxxx** [comment]
Thanks Bro!

**Comment by happydasch** [comment]
you are welcome, btw. the backfill functionality in btoandav20 allows you to fetch data from oanda without any limits of lines count (like 500 in the original store)
