### ISSUE TITLE
Which Features are Missing?

### ISSUE THREAD

**Issue by haimivan** [ftomassetti/backtrader-oandav20#4]
Hi,

may I ask you

1. which features are missing presently?
2. how long it may take to add them?
3. where beginners could help?

Thanks!

**Comment by ftomassetti** [comment]
When in doubt there are things that are always needed: documentation & examples :)
They are very valuable and they are so frequently overlooked

**Comment by happydasch** [comment]
The current state is, that basic functionality is working, like accessing the oanda v20 api, streaming prices, streaming events, creating market orders. There are sizer which can calculate a correct position size based on cash, percents for the traded symbols.

Besides documentation and examples, also the different order types needs testing.

**Comment by happydasch** [comment]
most of the functionality described for the oandastore in the backtrader documentation is supported:

https://www.backtrader.com/docu/live/oanda/oanda.html

The only thing that needs testing are the different order types:

        Order.Market (works)
        Order.Limit (should work)
        Order.Stop (should work)
        Order.StopLimit (using Stop and upperBound / lowerBound prices) (no usecase to test it)
        Order.StopTrail (no usecase to test it)
        Bracket orders are supported by using the takeprofit and stoploss order members and creating internally simulated orders. (should work, but needs testing for processing of transactions generated by stop loss or take profit)


What may cause issues:

If you get margin related transactions, these may not be processed correctly. Closing trades or positions which were opened by backtrader externally will break things. Creating orders from outside backtrader will break things.

**Comment by happydasch** [comment]
One thing, that is new:

4 different sizers:

OandaV20Percent - returns position size which matches the percent amount of total cash
OandaV20Cash - return position size which matches the cash amount
OandaV20RiskPercent - returns position size which matches the total risk in percent of total amount (max stop loss)
OandaV20RiskCash - returns position size which matches the total risk in percent of total amount (max stop loss)

**Comment by happydasch** [comment]
To get notifications of trades and orders outside market hours, the cerebro setting quicknotify would provide the notifications without new data.

**Comment by happydasch** [comment]
Order.Limit works, tested it in buy and sell brackets with a stop loss price.

**Comment by haimivan** [comment]
Hi, is there any possibility to test during the weekend, when all OANDA markets are closed?

**Comment by happydasch** [comment]
You can access the api, but trading is not possible, i think. Also there is no feed data coming, so there wouldn't happen anything.

**Comment by happydasch** [comment]
At the start, it will fetch currently open positions and create a order with the positions data. So backtrader knows, how many units are open. This way, when you call close in your strategy, the correct amount of open trades will get closed. The values will match. 

You should use a dedicated account for api trading and never open / close positions / trades from outside backtrader. This will break the internal positions value.

**Comment by happydasch** [comment]
I put all questions, faqs, answers into this issue, so we can later create some documentation from this.

**Comment by happydasch** [comment]
Oanda v20 supports:

Aggregate of 20 connections

currently we use:

stream events - 1 connection
stream prices - n connections (depending on count of data feeds, for every data feed one connection is used)
api query - 1 connection (account info, position info, etc.)

**Comment by happydasch** [comment]
Order.Market (works)
    Order.Limit (works)
    Order.Stop (should work)
    Order.StopLimit (using Stop and upperBound / lowerBound prices) (no usecase to test it)
    Order.StopTrail (no usecase to test it)
    Bracket orders are supported by using the takeprofit and stoploss order members and creating internally simulated orders. (works)

**Comment by happydasch** [comment]
New feature: backfill now works with start end end dates, this can be used for backtesting

**Comment by happydasch** [comment]
New feature: external orders and trades being closed should will be recreated.This is now being done if use_positions = True is set in broker. With this, the store will recreate all externally filled trades as orders in backtrader.

**Comment by happydasch** [comment]
with use_positions=False, nothing will be loaded at the beginning (open positions), no external generated transactions will be processed.

**Comment by hphsu** [comment]
An installation document would be nice, I run into following error while trying to run the example, any idea what's wrong?
```
$ python oandav20test.py
Traceback (most recent call last):
  File "oandav20test.py", line 12, in <module>
    import btoandav20
  File "/Users/hhsu/.pyenv/versions/3.6.6/lib/python3.6/site-packages/btoandav20-0.0.4-py3.6.egg/btoandav20/__init__.py", line 6, in <module>
ImportError: cannot import name 'feeds'
```

**Comment by happydasch** [comment]
@hphsu 

* check if v20 is installed
* for installation, just copy the btoandav20 directory into the path where your script is located at.

**Comment by happydasch** [comment]
@hphsu you can also look at this thread: https://community.backtrader.com/topic/1570/oanda-data-feed/10

**Comment by hphsu** [comment]
I follow your direction but still keep getting this error. Later I resolved this by installing pyyaml (pip install pyyaml) package. (who would have thought this error is due to a missing yaml package).  Anyway I finally get this to work. thanks for help @happydasch 


```
$ python oandav20test.py
Traceback (most recent call last):
  File "oandav20test.py", line 14, in <module>
    StoreCls = btoandav20.stores.OandaV20Store
AttributeError: module 'btoandav20.stores' has no attribute 'OandaV20Store'
```

**Comment by happydasch** [comment]
closing this, since not used anymore
