### ISSUE TITLE
Get open orders?

### ISSUE THREAD

**Issue by Kayne3** [ftomassetti/backtrader-oandav20#42]
Hi, 
I would like to know if there is some way to get open orders on start-up?

My example is this:
- My strategy opens a bracket order. 
- Mainside is executed and the stop side and limit side are accepted and working. 
- I stop the script (my strategy runs on a daily timeframe, hence, only wanting to run it at a certain time once a day)
- Upon the next resumption of the script, I can get the position data/info of the executed mainside, but nothing about the other two orders that are open and working in the market still.

I would like to be able to re-populate my order book with the currently open orders per data every time I run the script. Is this possible, any help?

Thanks in advance.

**Comment by happydasch** [comment]
btoandav20 will restore the open positions when starting. It will open a trade with the total amount of open position for every instrument. 

Take a look at the use_positions parameter for the broker

https://github.com/ftomassetti/backtrader-oandav20/blob/1c27ed10298a03eff8d4d0083948fb02ddd8001f/btoandav20/brokers/oandav20broker.py#L42

**Comment by happydasch** [comment]
orders which are not filled, will not get restored.

**Comment by Kayne3** [comment]
> orders which are not filled, will not get restored.

I see. I am using the "use_positions=True" parameter in the broker instance, but as I explained and you covered above, this only repopulates the existing executed/filled orders - which for brackets is only the mainside order.

Please correct me if I'm wrong, but the Oanda V20 API does allow to retrieve all open orders for an account. Would it be possible to get support in btoandav20 for this, as I cannot see a way to continue without being able to repopulate my open orders upon script resumption?

**Comment by happydasch** [comment]
> > orders which are not filled, will not get restored.
> 
> I see. I am using the "use_positions=True" parameter in the broker instance, but as I explained and you covered above, this only repopulates the existing executed/filled orders - which for brackets is only the mainside order.
> 
> Please correct me if I'm wrong, but the Oanda V20 API does allow to retrieve all open orders for an account. Would it be possible to get support in btoandav20 for this, as I cannot see a way to continue without being able to repopulate my open orders upon script resumption?

You are right, it will not restore all but only the positions open (they may be opened by different trades). So it will create one trade with the total amount of open positions. You would have to do it manually.
The problem is restoring the order.ref (so you know in backtrader which orders belong together). 

You would basically fetch all open trades before start and then create the trades according your needs.

**Comment by happydasch** [comment]
> Please correct me if I'm wrong, but the Oanda V20 API does allow to retrieve all open orders for an account. Would it be possible to get support in btoandav20 for this, as I cannot see a way to continue without being able to repopulate my open orders upon script resumption?
> 

You can access the oanda api by using the store:

> store.oapi 

This is the oanda v20 connection object.

You can find examples for the v20 api access here:

> https://github.com/oanda/v20-python-samples

Hope this helps you.

**Comment by k0286** [comment]
Hello, 
I've some confuse about this issue.

IMHO, the issue #15 and this issue are vary similar, and the the README shows that this project is available to **Replace pending orders**.  So I'm not sure if the pending orders  are reproduced or not.

@happydasch 
Can you give more details?  It seems that I misunderstand the "Replace pending orders" means.

thank you!

**Comment by happydasch** [comment]
@k0286 i am not really sure about your question. for pending orders, these are orders which are not filled yet. so there is no trade open yet or which were not filled yet like SL or TP orders for open trades.

**Comment by happydasch** [comment]
what will not be possible is recreating orders bbetween different instances. so if you close a running instance of backtrader, it will not be possible to recreate all pending orders (which are not filled yet). it is only possible to recreate open trades without any information of pending orders.

**Comment by k0286** [comment]
> 
> 
> @k0286 i am not really sure about your question. for pending orders, these are orders which are not filled yet. so there is no trade open yet or which were not filled yet like SL or TP orders for open trades.

Thanks for your reply!

According to your description, bto store doesn't synchronize the trades/orders history or states from the oanda server side.

So if I want to check whether the pending orders on the server side  are existed  or not,  the only way is to call `oapi` manually, right?

**Comment by happydasch** [comment]
> So if I want to check whether the pending orders on the server side are existed or not, the only way is to call `oapi` manually, right?

Yes, correct
