### ISSUE TITLE
Orders/Trades do not Appear in Oanda Transaction History 

### ISSUE THREAD

**Issue by haimivan** [ftomassetti/backtrader-oandav20#5]
Hi,

I supply the test example with:
--token [token] --account [account] --data0 EUR_USD --timeframe Minutes --compression 1 --trade

I would expect that a trade would be executed at the OANDA backend accordingly.

Unfortunately, in the OANDA transaction history, I cannot find the order/trade (see attached log).

[output.txt](https://github.com/ftomassetti/backtrader-oandav20/files/1846464/output.txt)

**Comment by happydasch** [comment]
You need to use the Oanda Broker, use the —Broker argument and set it to True

**Comment by haimivan** [comment]
thanks
