### ISSUE TITLE
Issue in oandav20store.py line 879 for Python3

### ISSUE THREAD

**Issue by jimfoo88** [ftomassetti/backtrader-oandav20#55]
Hi,

Please refer to line 879: 
`del self._trades[key]`

you should not delete an item while looping a dict or orderedDict, it will throws this exception:
```
File "/media/jimfoo88/Media/linux_files/anaconda3/envs/jimtfgpu/lib/python3.8/site-packages/btoandav20/stores/oandav20store.py", line 894, in _process_trades
    for key, value in self._trades.items():
RuntimeError: OrderedDict mutated during iteration

```

Please make a shallow copy before iterating the items, like this: `self._trades.copy().items()`

**Comment by jimfoo88** [comment]
thanks for fixing the issue

**Comment by happydasch** [comment]
thanks for showing this issue :) will commit this into this repository, too

**Comment by jimfoo88** [comment]
No probs, glad to help
