### ISSUE TITLE
Exception during Trading

### ISSUE THREAD

**Issue by haimivan** [ftomassetti/backtrader-oandav20#6]
calling with:
     --data0 EUR_USD --timeframe Minutes --compression 1 --trade --broker

leads to:

    Exception in thread Thread-18:
    Traceback (most recent call last):
      File "/home/user/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
        self.run()
      File "/home/user/anaconda3/lib/python3.6/threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "/home/user/PycharmProjects/0362-backtrader-oandav20-in-between/btoandav20/stores/oandav20store.py", line 533, in _t_order_create
        if self._transactions.has_key(oid):
    AttributeError: 'collections.defaultdict' object has no attribute 'has_key'

code fragment:

            # use the id of the transaction which created
            # the order, this will be the order id
            oid = o.id
            self._orders[oid] = oref

            # process transactions after id mapping was added
            if self._transactions.has_key(oid):                     #<<-----------------exception
                tpending = self._transactions.pop(oid)
                for trans in tpending:
                    self._process_transaction(oid, trans)

**Comment by happydasch** [comment]
I pushed a fix, has_key is deprecated in python3 i only tested it with python 2.7, give me some feedback, if that fixed the issue

**Comment by haimivan** [comment]
It seemed to help. 

Bravo!
