### ISSUE TITLE
Market Order With Price Supplied

### ISSUE THREAD

**Issue by haimivan** [ftomassetti/backtrader-oandav20#7]
Hi,

perhaps this is a standard Backtrader behaviour, but anyhow:

In the example, I can see the order statement:

                    self.order = self.buy(size=self.p.stake,
                                          exectype=self.p.exectype,
                                          price=price,
                                          valid=self.p.valid)

It gets executed with a `market` order in the plain vanilla case:

                    print("set up buy order, exectype:", self.p.exectype)
                    from backtrader import order; print("OrderBase.ExecTypes:", order.OrderBase.ExecTypes)

    set up buy order, exectype: 0
    OrderBase.ExecTypes: ['Market', 'Close', 'Limit', 'Stop', 'StopLimit', 'StopTrail', 'StopTrailLimit', 'Historical']

For me it seems a little bit contradicting that I as a user am allowed to create an order with `market` conditions and that I can also supply a price.

I would expect that I can either supply a `price` or give a `market` order - but not both.

**Comment by happydasch** [comment]
The price will only be used if its not a market order. So i think, its fine, if you provide it, but it won't be used. It's up to you to provide this data, so don't. Just follow the backtrader documentation in this case.

 At the moment, i work on other order types (i add stop loss and take profit), they will not be handled correctly at the moment. I commited my current code a few minutes ago, maybe give that a try.
