### ISSUE TITLE
backfill with more than 500 rows

### ISSUE THREAD

**Issue by happydasch** [ftomassetti/backtrader-oandav20#9]
It should be possible to fill data with more than 500 rows. see attached example of historical oanda data downloader on how to do it. 

[oanda_download.py.txt](https://github.com/ftomassetti/backtrader-oandav20/files/1851934/oanda_download.py.txt)

**Comment by happydasch** [comment]
Oanda store can now be used for backtesting. It can now fetch any data from history for a specified instrument

**Comment by huuquynh** [comment]
Is there any way to load recent rows at the backtrader's starting then continue receive live data for running algorithm, man? I read the code, but only download history for backtest and stop.

**Comment by happydasch** [comment]
absolutly. just the param fromdate to the date you want to backfill data from and then ensure that the param historical is not True. This will backfill data from the given date and when backfill  is done it will switch to live data.

**Comment by huuquynh** [comment]
Ah, I see. Because I based on yours to implement my own data store. And just read the code to understand the logic.

Thank you very much!
